### ISSUE TITLE
Adding attributes to function compilation

### ISSUE THREAD

**Issue by ChrisRackauckas** [IntelLabs/CompilerTools.jl#1]
Hey, I was wondering if this tool could be extended so that one could specify for the compiler to either add the command -offload-attribute-target=mic or add __attribute__((target(mic))) in front of functions. I have a code which is similar in both Julia and C and am wondering if I could use this code to compile simple functions for the Xeon Phi. The only real difference between the two codes is this attribute. Let me know if anyone is interested in perusing this and I will give some example codes.

**Comment by ehsantn** [comment]
We used to have some Xeon Phi support in ParallelAccelerator that can be revived. Adding attributes is easy but the arrays need to be copied back and forth properly. @ninegua knows more.

**Comment by ChrisRackauckas** [comment]
I have code for performing certain Monte Carlo calculations on the Phi (solving stochastic differential equations). They simply require a function pointer do all of the data handling. I have already bound everything to Julia via ccall, but as of now that function to be integrated has to be specified in C. However, if I could get a Phi-compatible function compiled from a simple Julia function and pass the pointer via Julia's ccall to interface then my library will be able to be used strictly from Julia.

Note that since it's just a simple integrated, compatibility with only standard math function is required. If you have anything in the works that could do this, I've love to give it a try!

**Comment by ninegua** [comment]
Xeon Phi support wasn't a priority in our public release of ParallelAccelerator, and indeed we had to take out code that is related to the scheduler and runtime that is not yet open source. But I do believe it's not too difficult to get back some Phi compatibility, compile on host and run on Xeon Phi through OpenMP offload. It may or may not fit your particular work flow, but I'll work on this a bit and let you know. @ChrisRackauckas

**Comment by ninegua** [comment]
@ChrisRackauckas I have a question on how you actually run the Phi code from Julia. Did you have to use icc to compile Julia with `-offload` flag? I am having trouble loading code compiled with `-offload-attribute-target=mic` flag into Julia using ccall, it gives me this error:
```
offload error: unexpected embedded target binary type, expected either an executable or shared library
```
Previously we had to compile Julia using icc to get around it, not sure if you ran into similar issues, and wonder how you solved it.

**Comment by leonardt** [comment]
@ninegua I remember seeing this not sure if it's for the same reason but I needed to add the generated .so to LD_LIBRARY_PATH. You can either use prospect dev mode and manually update it or programmatically add the tmpdir to ENV inside cgen.  You might need to this for the array runtime too.

**Comment by DrTodd13** [comment]
Isn't this the issue where you need the containing the shared object in LD_LIBRARY_PATH?

**Comment by DrTodd13** [comment]
Lenny beat me to it by 12 seconds. :)

**Comment by ChrisRackauckas** [comment]
[I wrote a tutorial on my blog on how I did it](http://www.stochasticlifestyle.com/interfacing-xeon-phi-via-julia/). I was able to compile it with -qoffload -offload-attribute-target=mic (so that way I didn't have to add attribute tags everywhere) and then I had to set the LD_LIBRARY_PATH in Julia.

**Comment by ninegua** [comment]
Thank you all for the clue. With this tip, I (partially) brought back MIC support to ParallelAccelerator (this thread really belongs there since it has nothing to do with CompilerTools) in commit [ec49183](https://github.com/IntelLabs/ParallelAccelerator.jl/commit/ec49183449d1433bb67bce4f48c62e7f1a1f7426). There is at least one know bug that it doesn't work for blackscholes, but it works for a few others (laplace3d, gaussianblur) that I tried. I'll continue to tinker a little bit.

In summary, you'll need to set environment variable `PROSPECT_MODE=offload1` to run a program on MIC card. If you want to look at the generated C code, it is available in `ParallelAccelerator/deps/generated` directory when you also set `PROSPECT_DEV_MODE=1`. For MIC offload, all array values go through some contrived data transfer scheme implemented in [`ParallelAccelerator/deps/include/j2c-array.h`](https://github.com/IntelLabs/ParallelAccelerator.jl/blob/master/deps/include/j2c-array.h) for two reasons: 1. we want GC for j2c-arrays; 2. we want to handle nested arrays. Otherwise the C code would look reasonably clean code with OMP offload pragma. 

Let me know if this is sufficient for your use. @ChrisRackauckas

**Comment by ninegua** [comment]
@ChrisRackauckas I made a few other commits to tighten up MIC support. Now pretty much everything that runs normally with ParallelAccelerator should also run on MIC when `PROSPECT_MODE=offload1`. I'm closing this issue now, and if you have further questions please file a ticket on [ParallelAccelerator's issue tracker](https://github.com/IntelLabs/ParallelAccelerator.jl/issues). Thanks!

**Comment by ChrisRackauckas** [comment]
Cool thanks. I'll give it a try on SuperMIC in a few weeks and if I have issues take them over to ParallelAccelerator. Sorry about that, I assumed that since this was a compilation question I would go directly to the compilation package. Hope it works!
